### ISSUE TITLE
Undeclare booleanValue

### ISSUE THREAD

**Issue by njappboy** [chilts/12factor-config#6]
@chilts can you declare booleanValue https://github.com/chilts/12factor-config/blob/6f8e8f169f8f062381edaf617d5281bbd1421db2/index.js#L64

**Comment by chilts** [comment]
Thanks for spotting this. :) I'll fix it quick.

**Comment by chilts** [comment]
Released as v1.3.1 : https://www.npmjs.com/package/12factor-config

Thanks again @njappboy! :)
