### ISSUE TITLE
"you really shouldn't use this, but some people/packages do"

### ISSUE THREAD

**Issue by moimikey** [chilts/12factor-config#7]
This isn't an issue, but I wanted to get your opinon @chilts on why you felt this way regarding an `env` config key.

**Comment by chilts** [comment]
I just feel that using a magical ENV VAR such as `NODE_ENV` can be somewhat puzzling. For example, Express will do different things depending on whether `NODE_ENV` is set to `dev` or `prod`. If you didn't know this and you set it to be one of the above, or something different, then a change in functionality is going to be hard to track down. This comment is really just to tell you to be explicit about what you set.

So, in summary, I feel that your application is the only thing that should read and act on config variables. Libraries shouldn't. Instead, the application should pass any config the library requires explicitly. If that comes from an environment variable or a default in the code, that's up to the applications.

Thanks for opening (and closing) this issue so I could write a few things down. Should I add something along these lines to the ReadMe? Thanks again.

**Comment by moimikey** [comment]
@chilts thank _you_ for answering back! i think it would be influential to others that may have a similar question about it or may uninhibitedly include environment checking code to their library. It could be as simple as linking to this thread.

In front end application build pipelines, it's seemingly common place to do something like `NODE_ENV=development node server.js`. `server.js` may have logic in it that separates things like plugins or middleware, but only load them if the `NODE_ENV` is `x` or `y`. This is of course directly against 12-factor and I'm wanting to come up with a 12-factor way to acheive this, especially with the amount of different conditions involved. Is it still considered scalable whereby your command looks like `VAR=1 VAR=2 VAR=3 .... VAR=98 VAR=99 node server.js`? Or is that an immediate sign that it's simply being done in a less efficient or incorrect way?

Thanks!
